config_version: 0.0.0
bad_versions:
  - 2022.12.475.0
  - 2022.12.583.0
log_patterns_by_issue:
  - search_file: daemon.log
    issue_type:
      "FW":
        search_term:
          - "WARN warp::dns::doh] DoH request failed: hyper::Error(Io, Kind(BrokenPipe)"
          - 'WARN warp::dns::doh] DoH request failed: hyper::Error(Connect, ConnectError("tcp connect error'
      "PORTBLOCK":
        search_term:
          - 'DEBUG warp::warp: Connect finished Err(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })'
      "PORT53":
        search_term:
          - 'Unable to bind local UDP socket error=Os { code: 48, kind: AddrInUse, message: "Address already in use" }'
      "BADCERT":
        search_term:
          - "invalid peer certificate"
          - "BadCertificate"
  - search_file: ps.txt
    issue_type:
      "FW":
        search_term:
          - Netskope
          - ESET Cyber
          - SophosNetFilter
      "VPN":
        search_term:
          - OpenVPN
          - sophos
          - FortiClient
          - Fortinet
          - SophosAgent
          - vpnui
          - AnyConnect
          - Mullvad
          - WireGuard
          - AWSVPNClient
          - OpenDNS
          - vpnagent
          - openvpnserv
          - FortiSSLVPNdaemon
          - Umbrella
          - PanGPA
          - PanGPS
          - ExpressVPN
          - OpenFortiGUI
          - VPN.appex
reply_by_issue_type:
  "FW":
    message: |
      There May be a Firewall or service blocking required ports or performing TSL inspection.
      Please verify all the required ports are unblocked https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/firewall/
  "VPN":
    message: |
      Warp can run alongside legacy VPN solutions provided the following requirements are met, and configuration changes are made which are listed in the [Legacy VPN compatibility documentation](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/vpn/)
  "PORT53":
    message: |
      This indicates something else is bound to localhost port 53 and likely also
      trying to do DNS interception or run a local DNS proxy.
  "ROUTE":
    message: |
      A large number of route changes suggests that there is another application such as a third party VPN that is competing with the Warp client
  "PORTBLOCK":
    message: |
      This is a Linux permission configuration issue on the device and needs to be resolved by the customer.
      This means the UDP connection to the edge was established, but one of the steps afterward failed for lack of permissions.
      Typically this is because something in AppArmor or SELinux is denying a capability we need to operate, probably CAP_NET_ADMIN or CAP_NET_RAW. 
      It can also happen if you are trying to run this in a Docker container and have not specified the correct permissions. Check `auditd` for denials.
      On Linux we use `setsockopt` to set SO_MARK on the UDP socket, which can fail on permissions. We can also be denied trying to open /dev/net/tun to create the tunnel device. 
      We can also fail trying to send netlink commands to set kernel routing rules.
  "BADCERT":
    message: |
      Please visit zero-trust-client.cloudflareclient.com/v0/client_config in the browser and look at the certificate used to sign the HTTPS connection.
      Please verify https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/deployment/firewall/ for a list of domains, IPs and ports that must be excluded from Firewall or TLS inspection.
  "BYTES":
    message: |
      The not enough bytes error is fixed in version 2022.9.214.1
      Update to version post fix later than 2022.9.214.1 and verify whether issue persists.
  "BADVERSION":
    message: |
      It appears that you are running a version that has been flagged as a bad version due to issues that were not found in prerelease testing.
      This version has since been removed from the release site.
  "OUTDATED_VERSION":
    message: |
      "It appears that you are not running the latest version of the chosen release train.
      Please attempt to replicate the error using the latest available version according to the details below. "
  "SPLITTUNNEL":
    message: |
      The IP address assigned to the interface being used for the tunnel is not
      correctly excluded from the split tunnel configuration. \nPlease ensure this IP
      address (or range) is added to the split tunnel configuration for the warp profile
      used by this device. More details can be found at: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/private-net/connect-private-networks/#3-route-private-network-ips-through-warp"
  "EXCLUDE_EDITED":
    message: |
      It appears that a change has been made to the default split tunnel exclusions list has been edited. 
      We strongly advise against this as it can cause unintended issues and should only be done in the event that warp to tunnel routing is used. 
      Only the smallest subset of IP addresses have been removed from the exclusion list. 
      More details can be found at: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/private-net/connect-private-networks/#3-route-private-network-ips-through-warp"
